openapi: 3.0.0
info:
  title: Lightelligence API
  version: 1.0.0
  description: API Specification of OSRAM Lightelligence
  contact:
    email: support@lightelligence.io
servers:
  - url: 'https://api.lightelligence.io/v1'
    description: Production Environment
x-olt-servers:
  id:
    url: 'https://id.lightelligence.io/v1'
    description: OAuth2 Production Environment
security:
  - oAuthSample: []
components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: >-
            https://id.lightelligence.io/v1/id/auth/realms/olt/protocol/openid-connect/auth
          tokenUrl: >-
            https://id.lightelligence.io/v1/id/auth/realms/olt/protocol/openid-connect/token
          userInfoUrl: >-
            https://id.lightelligence.io/v1/id/auth/realms/olt/protocol/openid-connect/userinfo
          scopes: []
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Error: &ref_0
      type: object
      additionalProperties: false
      required:
        - errorCode
        - errorMessage
      properties:
        errorCode:
          type: string
          description: The error code.
          example: BILLING_FORBIDDEN
        errorMessage:
          type: string
          description: Error message with further details.
          example: You are not allowed to post events.
    PaymentSession:
      type: object
      additionalProperties: false
      required:
        - sdkVersion
        - shopperReference
        - origin
        - returnUrl
        - countryCode
      properties:
        sdkVersion:
          type: string
          description: Ayden SDK version used
          example: 1.9.2
        origin:
          type: string
          enum:
            - local
            - dev
            - int
            - preview
            - prod
          example: dev
        returnUrl:
          type: string
          description: Return URL relative to origin
          example: /checkout/completed
        countryCode:
          type: string
          description: The shopper country code according to ISO 3166-1 alpha-2
          example: NL
          minLength: 2
          maxLength: 3
        shopperReference:
          type: string
          format: uuid
          description: Shopper id used by the payment session
          example: 0f2f4b03-0426-4ffa-837b-751eff9a4d78
    PaymentPayload:
      type: object
      additionalProperties: false
      properties:
        paymentPayload:
          type: string
          description: Payload to be validated by the payment provider
          example: eyJ0ZXN0IjoiZXhhbXBsZSBvYmplY3Qgd2l0aG91dCByZWFsIGVzdHJ1Y3R1cmUifQ==
  responses:
    BadRequest:
      description: Bad Request response.
      content:
        application/json:
          schema: *ref_0
          example:
            errorCode: BILLING_BADREQUEST
            errorMessage: Request Body has to be an Object.
    Unauthorized:
      description: Unauthenticated response.
      content:
        application/json:
          schema: *ref_0
          example:
            errorCode: BILLING_UNAUTHORIZED
            errorMessage: User not authorized.
    Forbidden:
      description: Unauthorized response.
      content:
        application/json:
          schema: *ref_0
          example:
            errorCode: BILLING_FORBIDDEN
            errorMessage: User is not allowed to access resource.
    NotFound:
      description: Entity not found response.
      content:
        application/json:
          schema: *ref_0
          example:
            errorCode: BILLING_NOT_FOUND
            errorMessage: Payment method not found.
    InternalServerError:
      description: Internal Server Error response.
      content:
        application/json:
          schema: *ref_0
          example:
            errorCode: BILLING_INTERNAL_ERROR
            errorMessage: An internal server error occurred.
    ServiceUnavailable:
      description: Service Unavailable response.
      content:
        application/json:
          schema: *ref_0
          example:
            errorCode: BILLING_SERVICE_NOT_AVAILABLE
            errorMessage: Service is temporary unavailable.
tags: []
x-tagGroups:
  - name: Platform
    tags:
      - oauth
      - notifications
      - consumption
  - name: Tenants
    tags:
      - tenants
      - billing
      - cron
  - name: User Management
    collapsible: true
    tags:
      - users
      - user-management
      - roles-and-permissions
  - name: Application Management
    collapsible: true
    tags:
      - application-developer
      - applications
      - application-info
  - name: Device Management
    collapsible: true
    tags:
      - devices
      - device-types
      - certificates
      - firmwares
  - name: Device Actions
    collapsible: true
    tags:
      - events
      - rule-engine
      - firmware-installation
  - name: Device Data
    collapsible: true
    tags:
      - timeseries
      - ingest
      - streaming
  - name: Troubleshooting
    collapsible: true
    tags:
      - diagnostics
      - audit-logs
paths: {}
